server:
  port: 6060

spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      fail-fast: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  producer:
    auto-start: true
    topic: kafka-boot-test-topic
  consumer:
    auto-start: true
    topic: kafka-boot-test-topic
    group-id: Kafkassandra-group


