/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.malsolo.kafka.streams.trading.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CompanyShares extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 268221143514845819L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CompanyShares\",\"namespace\":\"com.malsolo.kafka.streams.trading.model\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"sector\",\"type\":\"string\"},{\"name\":\"industry\",\"type\":\"string\"},{\"name\":\"sharePriceTimestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"sharePrice\",\"type\":\"double\"},{\"name\":\"stockTransactionReferenceId\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CompanyShares> ENCODER =
      new BinaryMessageEncoder<CompanyShares>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CompanyShares> DECODER =
      new BinaryMessageDecoder<CompanyShares>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CompanyShares> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CompanyShares> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CompanyShares> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CompanyShares>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CompanyShares to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CompanyShares from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CompanyShares instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CompanyShares fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence sector;
   private java.lang.CharSequence industry;
   private long sharePriceTimestamp;
   private double sharePrice;
   private long stockTransactionReferenceId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CompanyShares() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sector The new value for sector
   * @param industry The new value for industry
   * @param sharePriceTimestamp The new value for sharePriceTimestamp
   * @param sharePrice The new value for sharePrice
   * @param stockTransactionReferenceId The new value for stockTransactionReferenceId
   */
  public CompanyShares(java.lang.CharSequence id, java.lang.CharSequence sector, java.lang.CharSequence industry, java.lang.Long sharePriceTimestamp, java.lang.Double sharePrice, java.lang.Long stockTransactionReferenceId) {
    this.id = id;
    this.sector = sector;
    this.industry = industry;
    this.sharePriceTimestamp = sharePriceTimestamp;
    this.sharePrice = sharePrice;
    this.stockTransactionReferenceId = stockTransactionReferenceId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sector;
    case 2: return industry;
    case 3: return sharePriceTimestamp;
    case 4: return sharePrice;
    case 5: return stockTransactionReferenceId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: sector = (java.lang.CharSequence)value$; break;
    case 2: industry = (java.lang.CharSequence)value$; break;
    case 3: sharePriceTimestamp = (java.lang.Long)value$; break;
    case 4: sharePrice = (java.lang.Double)value$; break;
    case 5: stockTransactionReferenceId = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sector' field.
   * @return The value of the 'sector' field.
   */
  public java.lang.CharSequence getSector() {
    return sector;
  }


  /**
   * Sets the value of the 'sector' field.
   * @param value the value to set.
   */
  public void setSector(java.lang.CharSequence value) {
    this.sector = value;
  }

  /**
   * Gets the value of the 'industry' field.
   * @return The value of the 'industry' field.
   */
  public java.lang.CharSequence getIndustry() {
    return industry;
  }


  /**
   * Sets the value of the 'industry' field.
   * @param value the value to set.
   */
  public void setIndustry(java.lang.CharSequence value) {
    this.industry = value;
  }

  /**
   * Gets the value of the 'sharePriceTimestamp' field.
   * @return The value of the 'sharePriceTimestamp' field.
   */
  public long getSharePriceTimestamp() {
    return sharePriceTimestamp;
  }


  /**
   * Sets the value of the 'sharePriceTimestamp' field.
   * @param value the value to set.
   */
  public void setSharePriceTimestamp(long value) {
    this.sharePriceTimestamp = value;
  }

  /**
   * Gets the value of the 'sharePrice' field.
   * @return The value of the 'sharePrice' field.
   */
  public double getSharePrice() {
    return sharePrice;
  }


  /**
   * Sets the value of the 'sharePrice' field.
   * @param value the value to set.
   */
  public void setSharePrice(double value) {
    this.sharePrice = value;
  }

  /**
   * Gets the value of the 'stockTransactionReferenceId' field.
   * @return The value of the 'stockTransactionReferenceId' field.
   */
  public long getStockTransactionReferenceId() {
    return stockTransactionReferenceId;
  }


  /**
   * Sets the value of the 'stockTransactionReferenceId' field.
   * @param value the value to set.
   */
  public void setStockTransactionReferenceId(long value) {
    this.stockTransactionReferenceId = value;
  }

  /**
   * Creates a new CompanyShares RecordBuilder.
   * @return A new CompanyShares RecordBuilder
   */
  public static com.malsolo.kafka.streams.trading.model.CompanyShares.Builder newBuilder() {
    return new com.malsolo.kafka.streams.trading.model.CompanyShares.Builder();
  }

  /**
   * Creates a new CompanyShares RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CompanyShares RecordBuilder
   */
  public static com.malsolo.kafka.streams.trading.model.CompanyShares.Builder newBuilder(com.malsolo.kafka.streams.trading.model.CompanyShares.Builder other) {
    if (other == null) {
      return new com.malsolo.kafka.streams.trading.model.CompanyShares.Builder();
    } else {
      return new com.malsolo.kafka.streams.trading.model.CompanyShares.Builder(other);
    }
  }

  /**
   * Creates a new CompanyShares RecordBuilder by copying an existing CompanyShares instance.
   * @param other The existing instance to copy.
   * @return A new CompanyShares RecordBuilder
   */
  public static com.malsolo.kafka.streams.trading.model.CompanyShares.Builder newBuilder(com.malsolo.kafka.streams.trading.model.CompanyShares other) {
    if (other == null) {
      return new com.malsolo.kafka.streams.trading.model.CompanyShares.Builder();
    } else {
      return new com.malsolo.kafka.streams.trading.model.CompanyShares.Builder(other);
    }
  }

  /**
   * RecordBuilder for CompanyShares instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CompanyShares>
    implements org.apache.avro.data.RecordBuilder<CompanyShares> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence sector;
    private java.lang.CharSequence industry;
    private long sharePriceTimestamp;
    private double sharePrice;
    private long stockTransactionReferenceId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.malsolo.kafka.streams.trading.model.CompanyShares.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sector)) {
        this.sector = data().deepCopy(fields()[1].schema(), other.sector);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.industry)) {
        this.industry = data().deepCopy(fields()[2].schema(), other.industry);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.sharePriceTimestamp)) {
        this.sharePriceTimestamp = data().deepCopy(fields()[3].schema(), other.sharePriceTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.sharePrice)) {
        this.sharePrice = data().deepCopy(fields()[4].schema(), other.sharePrice);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.stockTransactionReferenceId)) {
        this.stockTransactionReferenceId = data().deepCopy(fields()[5].schema(), other.stockTransactionReferenceId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing CompanyShares instance
     * @param other The existing instance to copy.
     */
    private Builder(com.malsolo.kafka.streams.trading.model.CompanyShares other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sector)) {
        this.sector = data().deepCopy(fields()[1].schema(), other.sector);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.industry)) {
        this.industry = data().deepCopy(fields()[2].schema(), other.industry);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sharePriceTimestamp)) {
        this.sharePriceTimestamp = data().deepCopy(fields()[3].schema(), other.sharePriceTimestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.sharePrice)) {
        this.sharePrice = data().deepCopy(fields()[4].schema(), other.sharePrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.stockTransactionReferenceId)) {
        this.stockTransactionReferenceId = data().deepCopy(fields()[5].schema(), other.stockTransactionReferenceId);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sector' field.
      * @return The value.
      */
    public java.lang.CharSequence getSector() {
      return sector;
    }


    /**
      * Sets the value of the 'sector' field.
      * @param value The value of 'sector'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder setSector(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sector = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sector' field has been set.
      * @return True if the 'sector' field has been set, false otherwise.
      */
    public boolean hasSector() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sector' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder clearSector() {
      sector = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'industry' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndustry() {
      return industry;
    }


    /**
      * Sets the value of the 'industry' field.
      * @param value The value of 'industry'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder setIndustry(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.industry = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'industry' field has been set.
      * @return True if the 'industry' field has been set, false otherwise.
      */
    public boolean hasIndustry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'industry' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder clearIndustry() {
      industry = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sharePriceTimestamp' field.
      * @return The value.
      */
    public long getSharePriceTimestamp() {
      return sharePriceTimestamp;
    }


    /**
      * Sets the value of the 'sharePriceTimestamp' field.
      * @param value The value of 'sharePriceTimestamp'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder setSharePriceTimestamp(long value) {
      validate(fields()[3], value);
      this.sharePriceTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'sharePriceTimestamp' field has been set.
      * @return True if the 'sharePriceTimestamp' field has been set, false otherwise.
      */
    public boolean hasSharePriceTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sharePriceTimestamp' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder clearSharePriceTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'sharePrice' field.
      * @return The value.
      */
    public double getSharePrice() {
      return sharePrice;
    }


    /**
      * Sets the value of the 'sharePrice' field.
      * @param value The value of 'sharePrice'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder setSharePrice(double value) {
      validate(fields()[4], value);
      this.sharePrice = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'sharePrice' field has been set.
      * @return True if the 'sharePrice' field has been set, false otherwise.
      */
    public boolean hasSharePrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'sharePrice' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder clearSharePrice() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'stockTransactionReferenceId' field.
      * @return The value.
      */
    public long getStockTransactionReferenceId() {
      return stockTransactionReferenceId;
    }


    /**
      * Sets the value of the 'stockTransactionReferenceId' field.
      * @param value The value of 'stockTransactionReferenceId'.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder setStockTransactionReferenceId(long value) {
      validate(fields()[5], value);
      this.stockTransactionReferenceId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'stockTransactionReferenceId' field has been set.
      * @return True if the 'stockTransactionReferenceId' field has been set, false otherwise.
      */
    public boolean hasStockTransactionReferenceId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'stockTransactionReferenceId' field.
      * @return This builder.
      */
    public com.malsolo.kafka.streams.trading.model.CompanyShares.Builder clearStockTransactionReferenceId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CompanyShares build() {
      try {
        CompanyShares record = new CompanyShares();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sector = fieldSetFlags()[1] ? this.sector : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.industry = fieldSetFlags()[2] ? this.industry : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sharePriceTimestamp = fieldSetFlags()[3] ? this.sharePriceTimestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.sharePrice = fieldSetFlags()[4] ? this.sharePrice : (java.lang.Double) defaultValue(fields()[4]);
        record.stockTransactionReferenceId = fieldSetFlags()[5] ? this.stockTransactionReferenceId : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CompanyShares>
    WRITER$ = (org.apache.avro.io.DatumWriter<CompanyShares>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CompanyShares>
    READER$ = (org.apache.avro.io.DatumReader<CompanyShares>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.sector);

    out.writeString(this.industry);

    out.writeLong(this.sharePriceTimestamp);

    out.writeDouble(this.sharePrice);

    out.writeLong(this.stockTransactionReferenceId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.sector = in.readString(this.sector instanceof Utf8 ? (Utf8)this.sector : null);

      this.industry = in.readString(this.industry instanceof Utf8 ? (Utf8)this.industry : null);

      this.sharePriceTimestamp = in.readLong();

      this.sharePrice = in.readDouble();

      this.stockTransactionReferenceId = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.sector = in.readString(this.sector instanceof Utf8 ? (Utf8)this.sector : null);
          break;

        case 2:
          this.industry = in.readString(this.industry instanceof Utf8 ? (Utf8)this.industry : null);
          break;

        case 3:
          this.sharePriceTimestamp = in.readLong();
          break;

        case 4:
          this.sharePrice = in.readDouble();
          break;

        case 5:
          this.stockTransactionReferenceId = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










